; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:arduino_nano_esp32]          ; 定義一個編譯環境，名字是 "arduino_nano_esp32"
platform = espressif32            ; 指定使用 Espressif32 平台（ESP32 系列晶片）
board = arduino_nano_esp32        ; 指定開發板型號 → Arduino Nano ESP32 (ESP32-S3)
framework = arduino               ; 使用 Arduino 框架（程式碼寫法像 Arduino IDE）

;---------------- 燒錄 & 串口監控 ----------------;
upload_protocol = esptool          ; 使用 esptool 來燒錄（ESP32 預設常用工具）
upload_speed = 921600              ; 上傳速度，預設是 115200
                                   ; ESP32-S3 通常可穩定跑 921600，能大幅縮短燒錄時間
upload_port = COM4                 ; 指定上傳埠口，依實際情況修改 (Windows 常見 COMx)
; monitor_speed = 115200           ; 序列監控 (Serial Monitor) 的鮑率
                                   ; 常見為 115200，需和程式裡的 Serial.begin() 一致

; 自動開啟序列監控時的輸出過濾器
; monitor_filters = 
;     default   ; 顯示基本輸出
;     time      ; 每行前面加上時間戳記
;     esp32_exception_decoder ; 自動解碼 ESP32 的錯誤訊息（Exception）

;---------------- 檔案系統 ----------------;
board_build.filesystem = littlefs  ; 使用 LittleFS 檔案系統（可存放圖片、設定檔等）
board_build.partitions = default.csv ; 使用預設的分割表（決定程式區/檔案系統區大小）

;---------------- 函式庫引用 ----------------;
lib_deps =                         ; 自動安裝並引用的函式庫清單
    adafruit/Adafruit NeoPixel@^1.11.0  ; 控制 NeoPixel LED 的函式庫
    kikuchan98/pngle@^1.0.0             ; 輕量級 PNG 解碼函式庫 (pngle)
    mathieucarbou/ESPAsyncWebServer @ ^3.6.0
    esphome/AsyncTCP @ ^3.3.2

;---------------- 編譯選項 ----------------;
build_flags = 
    -DBOARD_HAS_PSRAM               ; 告訴編譯器這塊板子有 PSRAM（外掛 SPI RAM）
                                     ; Arduino Nano ESP32 (S3) 有 8MB PSRAM
    -mfix-esp32-psram-cache-issue   ; 修正 ESP32 + PSRAM 快取問題
                                     ; 避免處理影像/大資料時發生當機或崩潰
    -DBOARD_USES_HW_GPIO_NUMBERS    ; 使用實際的 GPIO 腳位編號（而不是 Arduino 的 D0, D1, ... 定義）
    -Wl,-L"$PROJECT_DIR/lib/dither" ; 指定引入dither程式庫位置
    -Wl,--whole-archive -Wl,-l:libdither.a -Wl,--no-whole-archive ; dither程式庫設定




